[#139693829] Photos list on photos page
rangle/bridge-photo-map-app pull request #4
Opened 2017-02-16 23:55 UTC by clearlyTHUYDOAN

I worked on hooking up photos and displaying them in a list.

2017-02-17 00:27 UTC, melaniebrgr requested changes
Such a great start Thuy! We are definitely hitting the ground running thanks to this.

2017-02-17 00:27 UTC, melaniebrgr commented on .vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
Can this file be removed from the PR?

2017-02-17 00:27 UTC, melaniebrgr commented on src/actions/index.js
> +export const ACTION_TYPES = {
Can we split the action types and actions into different files?

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +import { getPhotos } from '../actions/index.js';
Don't need to include the '.js' at the end of your local module imports. The build/bundler tool is smart enough to know its javascript if you leave it pff.

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +const mapStateToProps = state => ({
Totally optional, but you can use destructuring here, e.g.
`const mapStateToProps = { photos } => ({ photos });`

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +const mapStateToProps = state => ({
I forgot you can return objects from arrow functions only if you wrap in parens -- nice.

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +export default connect(mapStateToProps, mapDispatchToProps)(App);
Another personal preference but I like keep the mapStateToProps mapDispatchToProps function and object near the connect function their used in.

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +  photos: React.PropTypes.array,
Consider making the photos prop required? Maybe getPhotos too, not sure.

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +          <div className="container">
As we talked about, let's pull out all styling for now.

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +class App extends Component {
Instead of App, let's make this it's own, more specific component... PhotoGallery? or just Gallery?

2017-02-17 00:27 UTC, melaniebrgr commented on src/app/app.js
> +import React, {Component} from 'react';
Spaces around Component, just to be similar to the others `{ Component }`

2017-02-17 00:27 UTC, melaniebrgr commented on src/components/image.js
> +const Image = (props) => (
You can destructure props here too, e.g. `const Image = { photos } => (...`

2017-02-17 00:27 UTC, melaniebrgr commented on src/components/image.js
> +        <div key={index} className="col s4">
Can be broken down into smaller components. Maybe leave out the card-content for now and create another component when you get to the story.

2017-02-17 00:27 UTC, melaniebrgr commented on src/components/image.js
> +const Image = (props) => (
Might need parens around the curly braces here^

2017-02-17 00:27 UTC, melaniebrgr commented on src/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
Maybe just comment out for now.

2017-02-17 00:27 UTC, melaniebrgr commented on src/reducers/photos.js
> +    return {...state, ...{list: payload.photos}};
Object destructuring! Awesome!

2017-02-17 01:39 UTC, melaniebrgr requested changes

2017-02-17 01:39 UTC, melaniebrgr commented on .vscode/launch.json
>  {
Can .gitignore?

2017-02-17 01:39 UTC, melaniebrgr approved these changes

2017-02-17 01:41 UTC, melaniebrgr approved these changes

2017-02-17 15:24 UTC, melaniebrgr commented on src/reducers/photos.js
> +    return {...state, ...{list: payload.photos}};
I was wrong about this^. It's actually an example of [object spread operator](http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html) use.

2017-02-18 15:58 UTC, merged

2017-02-18 15:58 UTC, pkanal commented
Had to merge this as admin because something wasnt right with Circle CI. Will look into that separately.