[#139693829] Complete photo search by keyword.
rangle/bridge-photo-map-app pull request #6
Opened 2017-02-21 02:32 UTC by clearlyTHUYDOAN

**Major**
- Added two new states: **1)** Keep track of search keyword, **2)** Keep track of status of search (so photo-gallery.js knows when to show the keyword searched as a title).
- Added two new actions: **1)** handleInput and **2)** searchPhotos.
- Added corresponding prop validations. 

**Minor**
- Changed app.js to photo-gallery.js
- Changed photo-gallery.js' folder to containers instead of app.

PS: Sorry I'm a chronic committer lmao. Probably just best to view file changes rather than per commit.

2017-02-21 16:41 UTC, AbdellaToronto commented
@clearlyTHUYDOAN - after merging in Melanie's code, you'll have to do a dreaded merge conflict resolution - you might want to wait for tonight's class to do that with Purvi's help!

2017-02-21 19:11 UTC, clearlyTHUYDOAN commented
@AbdellaToronto I'm half looking forward to it! This is the biggest dev group I've ever worked with so there's kind of a novelty about it. I'm sure it will wear off after though ;). Will get Purvi to help.

2017-02-22 01:35 UTC, melaniebrgr requested changes

2017-02-22 01:35 UTC, melaniebrgr commented on src/components/App/App.js
> +    const handleKeyword = (e) => this.props.handleInput(e.target.value);
This can come out of the render function, I think. The render function is fired every time the component is updated, so we are declaring the function every time the component renders (I think...). Better to declare it once outside of the render function.

2017-02-22 01:35 UTC, melaniebrgr commented on src/components/App/App.js
> +        <button onClick={handleSearch} type="button">Search</button>
Add type "submit" and make other changes so entering while focussed on input field makes request (clicking not required).

2017-02-22 01:35 UTC, melaniebrgr commented on src/components/App/App.js
> +        <h4>{this.props.status === true ? `#${this.props.search}` : ''}</h4>
Could be simplified to, {this.props.status && `#${this.props.search}`}
Only is this.props.status will the second part of the conditional be evaluated.

2017-02-22 01:35 UTC, melaniebrgr commented on src/containers/photo-gallery.js
> +import React, { Component } from 'react';
Can be removed from repo for now.

2017-02-22 01:35 UTC, melaniebrgr commented on src/reducers/photos.js
> +  searchKeyword: 'default',
Convert to empty string.

2017-02-22 01:35 UTC, melaniebrgr commented on src/reducers/photos.js
> +  search: 'default',
Ditto

2017-02-22 01:42 UTC, melaniebrgr approved these changes

2017-02-22 01:50 UTC, merged